#!/bin/bash

for TMP in `cat driver-list` ; do
    echo ${TMP}
    for FILE in `find ../raspberrypi-linux/ -type f -iname "*${TMP}*" | grep -vE "arch\/arm"` ; do 
        echo "          ${FILE}"
        break
        KEY='n'
        read -n1 -r -p "Copy file? (Y/n)..." KEY
        if [[ "${KEY}" == "" || "${KEY}" == "y" || "${KEY}" == "Y" ]] ; then
            FILEDIR=`echo ${FILE}|sed -E 's/\.\.\/raspberrypi-linux\/(.*)+\/[^\/]+\.[ch]/\1/g'`
            mkdir -p ${FILEDIR}
            cp -fv ${FILE} ${FILEDIR}/
        fi
    done
done
